export enum MainNavigation {
  CREATE_REPORT = "CREATE_REPORT",
  MANAGE_REPORT = "MANAGE_REPORT",
  DRILL_DOWN = "DRILL_DOWN",
  CONSOLIDATION = "CONSOLIDATION",
}

export enum SecondaryNavigation {
  START_FROM_SCRATCH = "START_FROM_SCRATCH",
  START_FROM_TEMPLATE = "START_FROM_TEMPLATE",
  IMPORT_FROM_SPREADSHEET = "IMPORT_FROM_SPREADSHEET",
  CREATE_CONSOLIDATED_REPORT = "CREATE_CONSOLIDATED_REPORT",
}
